Add the official MDX VSCode extension
mdx-js/mdx pull request #2098
Opened 2022-08-11 12:31 UTC by jasikpark

This adds a link to the "official vscode extension" https://github.com/mdx-js/vscode-mdx; https://github.com/silvenon/vscode-mdx is currently deprecated and links to that extension.

2022-08-11 13:54 UTC, remcohaszing reviewed
Thanks!

Maybe we should remove the link to the deprecated extension.

2022-08-11 16:04 UTC, wooorm commented
@remcohaszing seems good, can you make a suggestion on how to do that?

2022-08-12 08:42 UTC, remcohaszing requested changes

2022-08-12 08:42 UTC, remcohaszing commented on docs/docs/getting-started.server.mdx
>      try [`silvenon/vscode-mdx`](https://github.com/silvenon/vscode-mdx)
```suggestion
    try [`mdx-js/vscode-mdx`](https://github.com/mdx-js/vscode-mdx)
```

2022-08-12 09:03 UTC, wooorm approved these changes

2022-08-12 09:03 UTC, merged

2022-08-12 09:03 UTC, wooorm commented
Thank you!