Adds missing dependencies
mdx-js/mdx pull request #2256
Opened 2023-02-15 10:41 UTC by arcanis

- While `@mdx-js/mdx` doesn't directly depend on estree, the types that TypeScript generates do: look at the first line [here](https://unpkg.com/browse/@mdx-js/mdx@2.3.0/lib/plugin/recma-document.d.ts).

- It however directly depends on `hast` in its types ([here](https://github.com/mdx-js/mdx/blob/main/packages/mdx/lib/plugin/rehype-recma.js#L3)).

- Same for `source-map`, which is directly referenced [here](https://github.com/mdx-js/mdx/blob/main/packages/mdx/lib/plugin/recma-stringify.js#L3) and thus must be in `dependencies` rather than `devDependencies`

Fixes the following errors:

```
@mdx-js/mdx/lib/plugin/recma-document.d.ts(1,78): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-document.d.ts(1,216): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-document.d.ts(1,242): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-jsx-rewrite.d.ts(1,80): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-jsx-rewrite.d.ts(1,220): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-jsx-rewrite.d.ts(1,246): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-stringify.d.ts(1,79): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-stringify.d.ts(1,105): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/recma-stringify.d.ts(3,48): error TS2307: Cannot find module 'source-map' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/rehype-recma.d.ts(1,76): error TS2307: Cannot find module 'hast' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/rehype-recma.d.ts(1,196): error TS2307: Cannot find module 'hast' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/rehype-recma.d.ts(1,217): error TS2307: Cannot find module 'estree' or its corresponding type declarations.
@mdx-js/mdx/lib/plugin/rehype-recma.d.ts(3,27): error TS2307: Cannot find module 'hast' or its corresponding type declarations.
```

2023-02-15 11:14 UTC, remcohaszing requested changes
Thanks! Just one nit

2023-02-15 11:14 UTC, remcohaszing commented on packages/mdx/package.json
> +    "@types/estree": "^1.0.0",
Could you sort these alphabetically??

```suggestion
    "@types/estree": "^1.0.0",
    "@types/estree-jsx": "^1.0.0",
```

2023-02-15 11:16 UTC, arcanis commented on packages/mdx/package.json
> +    "@types/estree": "^1.0.0",
Of course 👍

2023-02-15 11:18 UTC, remcohaszing approved these changes

2023-02-15 20:09 UTC, wooorm approved these changes

2023-02-15 20:10 UTC, wooorm commented
Thanks! I’ll get back to the repo in ±10 days as I’m on holiday. OK?

P.S., how did you find these? Did people report it upstream? Or something else going on with Yarn or so?

2023-02-15 21:06 UTC, arcanis commented
No problem, thanks 👍

> P.S., how did you find these? Did people report it upstream? Or something else going on with Yarn or so?

I'm working on a fresh project with MDX support, and I happened to notice those errors pop up. It happens from time to time, it's the price to pay to not have to deal with undebuggable hoisting issues 🙂

2023-02-15 21:26 UTC, wooorm commented
Makes sense, thanks for raising it upstream!

2023-02-27 14:22 UTC, merged

2023-02-27 14:22 UTC, wooorm commented
Thanks! Will be a bit before I release this, bundled with some more changes likely!