Add Rspack as an optional peer dependency of loader
mdx-js/mdx pull request #2440
Opened 2024-02-13 02:30 UTC by chenjiahan

### Initial checklist

*   [x] I read the support docs 
*   [x] I read the contributing guide 
*   [x] I agree to follow the code of conduct 
*   [x] I searched issues and couldn’t find anything (or linked relevant results below) 
*   [x] If applicable, I’ve added docs and tests

### Description of changes

[Rspack](https://github.com/web-infra-dev/rspack) is a fast Rust-based web bundler and it is compatible with the architecture and ecosystem of webpack.

The `@mdx-js/loader` can be used with Rspack, but users will get a peer dependency warning, adding peerDependenciesMeta can resolve it. 

The same as: https://github.com/jantimon/html-webpack-plugin/pull/1829

2024-02-13 09:26 UTC, remcohaszing requested changes
I think all modern package managers install peer dependencies. They don’t install optional peer dependencies. The ones that don’t install peer dependencies merely show a warning, which is annoying, but not an error.

The `webpack` peer dependency exists for 2 reasons:

1. To indicate this is only compatible with Webpack versions 5 or greater.
2. For the type definitions, which users may or may not use. This is really similar to the `@types/react` peer dependency, which was discussed in #2281. We ended up not using optional peer dependencies there.

2024-02-13 09:26 UTC, remcohaszing commented on packages/loader/package.json
> +    "@rspack/core": "0.x || 1.x",
We don’t need a peer dependency for every framework that’s compatible with Webpack.

```suggestion
```

2024-02-13 09:26 UTC, remcohaszing commented on packages/loader/package.json
> +    },
This suggestion is related to the comment above.

```suggestion
```

2024-02-13 09:26 UTC, remcohaszing commented on packages/loader/readme.md
> +webpack / Rspack loader for MDX.
```suggestion
webpack loader for MDX.
```

2024-02-13 09:26 UTC, remcohaszing commented on packages/loader/readme.md
> +This integration is useful if you’re using webpack or Rspack (or another tool that uses webpack, such as Next.js).
```suggestion
This integration is useful if you’re using webpack (or another tool that uses
webpack, such as Next.js or Rspack).
```

2024-02-13 10:01 UTC, wooorm commented
typescript users that use rspack should likely still have webpack for types to work?
How likely is it that rspack users also use typescript?

If rspack supports webpack loaders, we don’t have to change the docs from webpack loader to webpack or rspack loader. Rspack users know that they can use webpack loaders.

2024-02-13 11:46 UTC, chenjiahan commented
Thank you for all the review comments, I have updated the PR content, just treating webpack as an optional peer dependency.
Some Rspack users will use TypeScript, but the types of webpack are not necessary in most scenarios, so it might be more appropriate to not install webpack.

2024-02-13 11:54 UTC, wooorm commented
> Some Rspack users will use TypeScript, but the types of webpack are not necessary in most scenarios, so it might be more appropriate to not install webpack.

How do you configure loaders such as this in rspack then?
It is IMO quite useful to have type safety for the options of this loader. Those types are in this package. And they need `webpack`

2024-02-13 12:06 UTC, wooorm commented
You can use TS outside of `.ts` files! With `@type` jsdoc. That’s what is done in the Use example here: https://github.com/mdx-js/mdx/tree/main/packages/loader#use. We recommend it to prevent mistakes.

2024-02-13 12:09 UTC, chenjiahan commented
This is a great method 👍🏻

As far as I know, `import('@mdx-js/loader').Options` does not depend on the types of webpack, webpack only provides the `LoaderContext` type, which will not affect `Options` type.

2024-02-13 12:18 UTC, remcohaszing commented
> As far as I know, `import('@mdx-js/loader').Options` does not depend on the types of webpack, webpack only provides the `LoaderContext` type, which will not affect `Options` type.

This is true. However, the package also exports the type of the loader, which does depend on the webpack types.

I’m indifferent on whether or not the webpack peer dependency should be optional.

I do welcome the documentation change.

2024-02-13 12:18 UTC, remcohaszing approved these changes

2024-02-13 18:32 UTC, merged

2024-02-13 18:33 UTC, wooorm commented
Thank you :)

2024-02-14 02:20 UTC, chenjiahan commented
Thank you for your time ❤️